### ISSUE TITLE
CORBA TIMEOUT while attempting to initialize USRP_UHD X310

### ISSUE THREAD

**Issue by RFComms** [RedhawkSDR/USRP_UHD#7]
I'm running REDHAWK 2.2.1 on Centos 7 and having difficulty communicating with a USRP X310 radio.  

UHD 13.10 is installed, the X310 has corresponding FPGA version, and uhd_find_devices and uhd_probe_usrp both work.  But when I run a node from either the IDE or terminal and try to connect to the X310 I see errors such as: 
```
$ nodeBooter -d /var/redhawk/sdr/dev/nodes/Node_2/2/1_A/DeviceManager.dcd.xml -debug 4
...
2018-12-17 11:55:19 ERROR DeviceManager:1673 - The following CORBA exception occurred: TIMEOUT while attempting to initialize Device USRP_UHD_1. Device registration with Device Manager failed
2018-12-17 11:55:19 FATAL USRP_UHD_1.system.Device:1347 - Device USRP_UHD_1, Failed initialization and registration, terminating execution
... 
2018-12-17 11:55:35 INFO  USRP_UHD_1.system.EventManager:801 - UNREGISTER REG-ID:c2f52534-74b2-45fb-91d9-c7fd2bab7d99 CHANNEL:IDM_Channel 
2018-12-17 11:55:36 WARN  DeviceManager:2774 - Child process USRP_UHD_1 (pid 31511) has terminated with signal 11
```

I noticed that REDHAWK 2.2.1 installs UHD 13.10, which responds very slowly to uhd_find_devices and uhd_probe_usrp.  Before installing 2.2.1 I tried UHD_3.14.0.0-248-ge758efc8 which responded much faster.  I'm not sure if this is relevant.  The Centos firewall is stopped. 
[20181218_DeviceManager_failure.txt](https://github.com/RedhawkSDR/USRP_UHD/files/2692628/20181218_DeviceManager_failure.txt)

Any suggestions? 

Thanks,

**Comment by RFComms** [comment]
Update:  Changing /var/redhawk/sdr/dev/mgr/DeviceManager.prf.xml CLIENT_WAIT_TIME from 10s (default) to 60s caused the CORBA Exception messages to occur 60s after starting the node (ie nodeBooter -d ...).  Previously they occurred 10s after starting. 

Any ideas?

**Comment by RFComms** [comment]
Update 2: 
I modified /var/redhawk/sdr/dev/devices/rh/USRP_UHD/USRP_UHD.prf.xml  to state the USRP's IP address.  It appears that BOTH changes were needed:  USRP_UHD.prf.xml  and DeviceManager.prf.xml .  Device Manager now appears to be stable for at least 10 minutes. 

```
<simple id="target::ip_address" name="ip_address" type="string">
      <description>IP address of the USRP for network connected devices.</description>
      <value>192.168.25.111</value>
    </simple>
```
I'll do more testing, but if this fixes the problem I'll close the ticket.

**Comment by jirwin-geon** [comment]
To clarify, what you've done is to set the `ip_address` element of the `target_device` property in both DeviceManager.dcd.xml and USRP_UHD.prf.xml? It should only be necessary to override in DeviceManager.dcd.xml, and if it behaves differently when you set it in USRP_UHD.prf.xml, that is a bug.

From the log file you originally included, it looks like it took ~6 seconds to find the device, and then the remaining time was then spent initializing the UHD device. From a quick test on a CentOS 6.10 system (uhd 3.7.3), launching rh.USRP_UHD with an X310 (in a different configuration), initialization takes about 9 seconds, which in your case would have run into the original 10s CORBA timeout. When it still failed with a 60s timeout, did it appear to have hung in initialization? How long does it take when you run `uhd_usrp_probe`?

It may be easier to debug by launching the USRP device in the Python sandbox (you may need to set additional values in the `config` dictionary):
```py
from ossie.utils import sb
config = {'target_device':{'ip_address':'192.168.25.111'}}
config['DEBUG_LEVEL'] = 4
usrp = sb.launch('rh.USRP_UHD', properties=config, timeout=60)
```
This allows you to work directly with the REDHAWK device without worrying about a node or domain configuration.

**Comment by RFComms** [comment]
Thanks J Irwin.  Here are my comments. 

> To clarify, what you've done is to set the ip_address element of the target_device property in both DeviceManager.dcd.xml and USRP_UHD.prf.xml?

**Comment by RFComms** [comment]
Thanks Justin.   Answers to your questions / suggestions: 

> To clarify, what you've done is to set the ip_address element of the target_device property in both DeviceManager.dcd.xml and USRP_UHD.prf.xml?   It should only be necessary to override in DeviceManager.dcd.xml, and if it behaves differently when you set it in USRP_UHD.prf.xml, that is a bug. 

1.  No bug.  I originally set the ip_address of the target_device in the USRP_UHD.prf.xml file only.   After your comment, I returned that file to default, and edited the Node properties through the IDE interface which updated the DeviceManager.dcd.xml.   

> From the log file you originally included, it looks like it took ~6 seconds to find the device, and then the remaining time was then spent initializing the UHD device. From a quick test ... initialization takes about 9 seconds, which ... would have run into the original 10s CORBA timeout. When it still failed with a 60s timeout, did it appear to have hung in initialization? How long does it take when you run uhd_usrp_probe?

After I changed timeout to 60s I also had to specify the ip_address.  After both changes the system started to work.  

I ran uhd_usrp_probe and saw: 
- first information returned after 8 seconds
- final information after 24 seconds

I'll close this issue now.
